import type { GameConfig } from '../models/contracts';

const PORT = Number(process.env.PORT || 25565);

const WORLD_SIZE = 100;
const BALL_COUNT = 20;
const DEFAULT_BALL_VALUE = 10;
const SIZE_INCREASE_PER_BALL = 0.05;
const MAX_SIZE_MULTIPLIER = 2.5;
const PLAYER_BASE_RADIUS = 0.52;
const PLAYER_COLLISION_PADDING = 0.2;
const PLAYER_CONSUME_SIZE_RATIO = 1.1;
const PLAYER_SCORE_TRANSFER_RATIO = 1;
const PLAYER_NAME_MAX_LENGTH = 16;
const PLAYER_NAME_MIN_LENGTH = 2;
const PLAYER_SPAWN_CLEARANCE = 8;
const BALL_CLEARANCE = 5;
const PLAYER_EDGE_MARGIN = 12;
const BALL_EDGE_MARGIN = 7;
const ARENA_WALL_PADDING = 0.7;
const ARENA_EDGE_SKIN = 0.12;
const ARENA_POST_COUNT = 10;
const ARENA_POST_RING_SCALE = 0.88;
const ARENA_POST_RADIUS = 0.72;
const MOVEMENT_THROTTLE_MS = 30;
const COLLECTION_THROTTLE_MS = 100;

const BALL_TYPES = {
  NORMAL: { value: 10, color: 0xffffff },
  GOLDEN: { value: 30, color: 0xffd700 },
  SPEED: { value: 5, color: 0x00ff00 },
};

const PLAYER_COLORS = [
  0xf5d76e,
  0x70d6ff,
  0xff9770,
  0x7bf1a8,
  0xff70a6,
  0xc7f464,
];

const RESPAWN_DELAY = 3000;
const PLAYER_RESPAWN_INVULNERABLE_MS = 2000;
const PLAYER_RECONNECT_GRACE_MS = 10000;
const SPEED_BOOST_DURATION_MS = 4000;
const SPEED_BOOST_MULTIPLIER = 1.35;
const DASH_COOLDOWN_MS = 1700;
const DASH_INVULNERABLE_MS = 220;
const CONSUME_INTENT_WINDOW_MS = 260;
const MAX_COLLECTION_DISTANCE = 5;

const SOCKET_CONFIG = {
  pingInterval: 10000,
  pingTimeout: 20000,
  cors: {
    origin: '*',
    methods: ['GET', 'POST'],
  },
};

const gameConfig: GameConfig = {
  PORT,
  WORLD_SIZE,
  BALL_COUNT,
  DEFAULT_BALL_VALUE,
  SIZE_INCREASE_PER_BALL,
  MAX_SIZE_MULTIPLIER,
  PLAYER_BASE_RADIUS,
  PLAYER_COLLISION_PADDING,
  PLAYER_CONSUME_SIZE_RATIO,
  PLAYER_SCORE_TRANSFER_RATIO,
  PLAYER_NAME_MAX_LENGTH,
  PLAYER_NAME_MIN_LENGTH,
  PLAYER_SPAWN_CLEARANCE,
  BALL_CLEARANCE,
  PLAYER_EDGE_MARGIN,
  BALL_EDGE_MARGIN,
  ARENA_WALL_PADDING,
  ARENA_EDGE_SKIN,
  ARENA_POST_COUNT,
  ARENA_POST_RING_SCALE,
  ARENA_POST_RADIUS,
  MOVEMENT_THROTTLE_MS,
  COLLECTION_THROTTLE_MS,
  BALL_TYPES,
  PLAYER_COLORS,
  RESPAWN_DELAY,
  PLAYER_RESPAWN_INVULNERABLE_MS,
  PLAYER_RECONNECT_GRACE_MS,
  SPEED_BOOST_DURATION_MS,
  SPEED_BOOST_MULTIPLIER,
  DASH_COOLDOWN_MS,
  DASH_INVULNERABLE_MS,
  CONSUME_INTENT_WINDOW_MS,
  MAX_COLLECTION_DISTANCE,
  SOCKET_CONFIG,
};

export default gameConfig;
