import type { GameConfig } from "@pegabola/shared";

const PORT = Number(process.env.PORT || 25_565);

const WORLD_SIZE = 100;
const MIN_BALL_COUNT = 18;
const MAX_BALL_COUNT = 96;
const BALLS_PER_PLAYER = 12;
const DEFAULT_BALL_VALUE = 10;
const SIZE_INCREASE_PER_BALL = 0.05;
const MAX_SIZE_MULTIPLIER = 2.5;
const PLAYER_BASE_RADIUS = 0.52;
const PLAYER_COLLISION_PADDING = 0.2;
const PLAYER_NAME_MAX_LENGTH = 16;
const PLAYER_NAME_MIN_LENGTH = 2;
const PLAYER_SPAWN_CLEARANCE = 8;
const BALL_CLEARANCE = 5;
const PLAYER_EDGE_MARGIN = 12;
const BALL_EDGE_MARGIN = 7;
const ARENA_WALL_PADDING = 0.7;
const ARENA_EDGE_SKIN = 0.12;
const ARENA_POST_COUNT = 10;
const ARENA_POST_RING_SCALE = 0.88;
const ARENA_POST_RADIUS = 0.72;
const ARENA_MONOLITH_COUNT = 8;
const ARENA_MONOLITH_RING_SCALE = 0.435;
const ARENA_MONOLITH_RADIUS = 1.2;
const ARENA_LANTERN_COUNT = 8;
const ARENA_LANTERN_RING_SCALE = 0.405;
const ARENA_LANTERN_RADIUS = 1.1;
const ARENA_BRAZIER_COUNT = 20;
const ARENA_BRAZIER_RING_SCALE = 0.79;
const ARENA_BRAZIER_RADIUS = 0.9;
const ARENA_PLANT_COUNT = 6;
const ARENA_PLANT_RING_SCALE = 0.285;
const ARENA_PLANT_RADIUS = 1;
const MOVEMENT_THROTTLE_MS = 30;
const COLLECTION_THROTTLE_MS = 100;
const PLAYER_MAX_HEALTH = 100;
const ATTACK_COOLDOWN_MS = 400;
const FIREBALL_SPEED = 44;
const FIREBALL_DAMAGE = 25;
const FIREBALL_RADIUS = 1.15;
const FIREBALL_LIFETIME_MS = 2800;

const BALL_TYPES = {
	NORMAL: { value: 10, color: 0xFF_FF_FF },
	GOLDEN: { value: 30, color: 0xFF_D7_00 },
	SPEED: { value: 5, color: 0x00_FF_00 },
	INFINITY_DASHES: { value: 15, color: 0xFF_00_FF },
	NIGHT_MODE: { value: 50, color: 0x3B_1C_6E },
	DAY_MODE: { value: 50, color: 0xFF_D1_66 },
};

const PLAYER_COLORS = [
	0xF5_D7_6E, 0x70_D6_FF, 0xFF_97_70, 0x7B_F1_A8, 0xFF_70_A6, 0xC7_F4_64,
];

const RESPAWN_DELAY = 3000;
const PLAYER_RESPAWN_INVULNERABLE_MS = 2000;
const PLAYER_RECONNECT_GRACE_MS = 10_000;
const SPEED_BOOST_DURATION_MS = 4000;
const SPEED_BOOST_MULTIPLIER = 1.35;
const DASH_COOLDOWN_MS = 1700;
const DASH_INVULNERABLE_MS = 220;
const INFINITY_DASHES_DURATION_MS = 5000;
const INFINITY_DASHES_CHANCE = 0.1;
const MAX_COLLECTION_DISTANCE = 5;

const SOCKET_CONFIG = {
	pingInterval: 10_000,
	pingTimeout: 20_000,
	cors: {
		origin: "*",
		methods: ["GET", "POST"],
	},
};

const gameConfig: GameConfig = {
	PORT,
	WORLD_SIZE,
	MIN_BALL_COUNT,
	MAX_BALL_COUNT,
	BALLS_PER_PLAYER,
	DEFAULT_BALL_VALUE,
	SIZE_INCREASE_PER_BALL,
	MAX_SIZE_MULTIPLIER,
	PLAYER_BASE_RADIUS,
	PLAYER_COLLISION_PADDING,
	PLAYER_NAME_MAX_LENGTH,
	PLAYER_NAME_MIN_LENGTH,
	PLAYER_SPAWN_CLEARANCE,
	BALL_CLEARANCE,
	PLAYER_EDGE_MARGIN,
	BALL_EDGE_MARGIN,
	ARENA_WALL_PADDING,
	ARENA_EDGE_SKIN,
	ARENA_POST_COUNT,
	ARENA_POST_RING_SCALE,
	ARENA_POST_RADIUS,
	ARENA_MONOLITH_COUNT,
	ARENA_MONOLITH_RING_SCALE,
	ARENA_MONOLITH_RADIUS,
	ARENA_LANTERN_COUNT,
	ARENA_LANTERN_RING_SCALE,
	ARENA_LANTERN_RADIUS,
	ARENA_BRAZIER_COUNT,
	ARENA_BRAZIER_RING_SCALE,
	ARENA_BRAZIER_RADIUS,
	ARENA_PLANT_COUNT,
	ARENA_PLANT_RING_SCALE,
	ARENA_PLANT_RADIUS,
	MOVEMENT_THROTTLE_MS,
	COLLECTION_THROTTLE_MS,
	PLAYER_MAX_HEALTH,
	ATTACK_COOLDOWN_MS,
	FIREBALL_SPEED,
	FIREBALL_DAMAGE,
	FIREBALL_RADIUS,
	FIREBALL_LIFETIME_MS,
	BALL_TYPES,
	PLAYER_COLORS,
	RESPAWN_DELAY,
	PLAYER_RESPAWN_INVULNERABLE_MS,
	PLAYER_RECONNECT_GRACE_MS,
	SPEED_BOOST_DURATION_MS,
	SPEED_BOOST_MULTIPLIER,
	DASH_COOLDOWN_MS,
	DASH_INVULNERABLE_MS,
	INFINITY_DASHES_DURATION_MS,
	INFINITY_DASHES_CHANCE,
	MAX_COLLECTION_DISTANCE,
	SOCKET_CONFIG,
};

export default gameConfig;
